# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    # - name: Build with MVN
    #   env:
    #     USERNAME: $GITHUB_ACTOR
    #     TOKEN: ${{ github.token }}
    #   run: ./mvnw build publish
    - name: Login Docker
      run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Docker Image
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER -Dspring-boot.build-image.builder=gcr.io/buildpacks/builder
    - name: Push Docker
      run: docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER